### PR TITLE
Suport node.js

### PR DESCRIPTION
**Pull request by Himura2la**
Please add this change to a minified version (if required (не уверен))

### CODE REVIEW

**Comment by Himura2la** [comment]
I'm trying to see the comparison between common time and ss-time, and I need to run this code in nodejs 
https://github.com/Himura2la/sscompare

**Comment by fakt309** [comment]
i've done. check it out.

**Comment by Himura2la** [comment]
wow, that was fast :)
I have another one coming

**Comment by fakt309** [comment]
It would be great if you could create a kind of clock app and put it on the google market or apple store. I could also help with advertising on sssecond.com If you have the opportunity.

**Comment by Himura2la** [comment]
I thought you already have Android covered with the Widget... 
My experience in Android development does not go further than building a debug APK, so I'm not sure I could help with Google Play publishing...

**Pull request merged**
